import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Affiliate Disclosure — Diffr",
  description:
    "FTC-required disclosure (16 CFR Part 255) of Diffr's affiliate relationships. Amazon Associates tag diffr20-20, eBay Partner Network campaign 5339154635.",
  robots: { index: true, follow: true },
};

export default function DiffrAffiliateDisclosurePage() {
  return (
    <main style={{ minHeight: "100vh", background: "#F0EBE3", color: "#2A2620", fontFamily: "var(--font-syne), Georgia, serif", padding: "0 0 80px" }}>
      <Header label="Affiliate Disclosure" />
      <article style={{ maxWidth: "760px", margin: "0 auto", padding: "64px 32px 0" }}>

        <h1 style={s.h1}>Affiliate Disclosure</h1>
        <p style={s.meta}>Last updated: May 26, 2026</p>

        <p style={s.p}>
          This page explains how Diffr makes money from the retailer links inside the iOS app. We&apos;re required to say this clearly under U.S. FTC rules (16 CFR Part 255) and we&apos;d want to say it anyway — opacity around financial incentives is the easiest way to lose trust.
        </p>

        <Hr />

        <H2>Short version</H2>
        <p style={s.p}>
          When you tap <strong>Buy on Amazon</strong> or <strong>Buy on eBay</strong> in the Diffr app and complete a qualifying purchase within 24 hours, those retailers pay us a small commission. <strong>Your price is identical to going to the retailer directly</strong> — the commission comes out of the retailer&apos;s margin, not your wallet.
        </p>
        <p style={s.p}>
          Commission revenue does <strong>not</strong> influence which brands Diffr recommends. The six-axis brand score (Heritage, Quality, Aesthetic, Innovation, Value, Cultural) is computed independently of which retailers carry the brand.
        </p>

        <Hr />

        <H2>Active affiliate partners</H2>
        <Table
          headers={["Partner", "Diffr ID", "Cookie window"]}
          rows={[
            [<><strong>Amazon Associates (US)</strong></>, <><code style={s.code}>diffr20-20</code></>, "24 hours"],
            [<><strong>eBay Partner Network (US)</strong></>, <>Campaign <code style={s.code}>5339154635</code></>, "24 hours"],
          ]}
        />
        <p style={s.p}>
          When you tap a buy button, the URL you land on contains our partner ID. The retailer&apos;s first-party cookie remembers that ID for 24 hours. If you check out within that window — even on items unrelated to the one we showed you — that purchase is credited to Diffr.
        </p>

        <Hr />

        <H2>What is NOT an affiliate link</H2>
        <p style={s.p}>
          The following retailers appear in the Diffr app, but tapping their buttons sends you to the retailer with <strong>no commission to Diffr</strong>:
        </p>
        <Ul>
          <Li>Walmart</Li>
          <Li>Best Buy</Li>
          <Li>REI · Backcountry · Dick&apos;s Sporting Goods</Li>
          <Li>Sephora · Ulta · Nordstrom · Farfetch · Net-A-Porter</Li>
          <Li>Williams-Sonoma · Crate &amp; Barrel</Li>
          <Li>Target · GameStop · Etsy</Li>
          <Li>Any brand&apos;s own official website</Li>
        </Ul>
        <p style={s.p}>
          We show these buttons to give you marketplace options. As we secure affiliate relationships with each retailer, we&apos;ll update this page. We will never silently flip a non-affiliate link into an affiliate one without disclosing it here first.
        </p>

        <Hr />

        <H2>Why this doesn&apos;t bias recommendations</H2>
        <p style={s.p}>
          A reasonable question: if Diffr earns more when you buy from Amazon, wouldn&apos;t we be tempted to push Amazon-friendly brands?
        </p>
        <p style={s.p}>Three reasons we don&apos;t:</p>
        <ol style={{ listStyle: "none", padding: 0, margin: "0 0 14px" }}>
          <li style={{ fontSize: "0.93rem", lineHeight: 1.8, color: "#2A2620", paddingLeft: "28px", marginBottom: "14px", position: "relative" }}>
            <span style={{ position: "absolute", left: 0, top: "0.1em", fontFamily: "var(--font-syne), sans-serif", fontWeight: 700, fontSize: "0.85rem", color: "#F0522C" }}>1.</span>
            <strong>The score is computed before retailer mapping.</strong> Each brand&apos;s six-axis score is generated by our recommendation engine using the brand&apos;s own data (founding story, product line breadth, community ratings, PSY-Match similarity to your profile). The retailer match step happens <em>after</em> — we look at the recommended brand and pick which retailers carry it.
          </li>
          <li style={{ fontSize: "0.93rem", lineHeight: 1.8, color: "#2A2620", paddingLeft: "28px", marginBottom: "14px", position: "relative" }}>
            <span style={{ position: "absolute", left: 0, top: "0.1em", fontFamily: "var(--font-syne), sans-serif", fontWeight: 700, fontSize: "0.85rem", color: "#F0522C" }}>2.</span>
            <strong>Commission rates are roughly comparable across the partners we list.</strong> Amazon Associates pays 1–10% depending on category (luxury beauty 1%, home &amp; kitchen 3%, fashion 4%); eBay Partner Network pays 1–4% depending on category. The difference is too small to be worth corrupting recommendations over.
          </li>
          <li style={{ fontSize: "0.93rem", lineHeight: 1.8, color: "#2A2620", paddingLeft: "28px", marginBottom: "14px", position: "relative" }}>
            <span style={{ position: "absolute", left: 0, top: "0.1em", fontFamily: "var(--font-syne), sans-serif", fontWeight: 700, fontSize: "0.85rem", color: "#F0522C" }}>3.</span>
            <strong>A bad recommendation costs us more than a missed commission.</strong> Diffr&apos;s premise is &ldquo;brands that won&apos;t punish you for being new.&rdquo; Recommending the wrong brand to make $0.50 in commission would shred the only reason anyone keeps using us.
          </li>
        </ol>
        <p style={s.p}>
          We&apos;d rather you trust the recommendation and buy <em>anything</em> through our links than lose trust and stop opening the app.
        </p>

        <Hr />

        <H2>How to verify (for the skeptical)</H2>
        <p style={s.p}>You can inspect the actual URLs the app generates:</p>
        <Ul>
          <Li>Amazon: <code style={{ ...s.code, wordBreak: "break-all" as const }}>https://www.amazon.com/s?k=&lt;brand&gt;+&lt;product&gt;&amp;tag=diffr20-20</code></Li>
          <Li>eBay: <code style={{ ...s.code, wordBreak: "break-all" as const }}>https://rover.ebay.com/rover/1/711-53200-19255-0/4?mpre=&lt;encoded ebay URL&gt;&amp;campid=5339154635&amp;toolid=10001</code></Li>
        </Ul>
        <p style={s.p}>
          Both are documented as our partner IDs in the respective programs&apos; publisher dashboards.
        </p>
        <p style={s.p}>
          If you don&apos;t want Diffr to earn commission on a purchase, just copy the brand name and paste it into your browser yourself.
        </p>

        <Hr />

        <H2>Upcoming changes we&apos;ll disclose here</H2>
        <p style={s.p}>
          We&apos;re applying to several other affiliate networks. When any of them activate, this page is updated <strong>before</strong> the new links go live in the app:
        </p>
        <Ul>
          <Li><strong>Walmart</strong> (via Impact) — application pending</Li>
          <Li><strong>Best Buy</strong> (via Impact) — not yet applied</Li>
          <Li><strong>REI, Backcountry, Dick&apos;s</strong> (Avantlink) — not yet applied</Li>
          <Li><strong>Sephora, Ulta</strong> (Rakuten) — not yet applied</Li>
        </Ul>

        <Hr />

        <H2>Amazon Product Advertising API</H2>
        <p style={s.p}>
          When Diffr&apos;s affiliate sales reach Amazon&apos;s threshold for unlocking the Product Advertising API (PA-API 5.0), we&apos;ll start using PA-API to pull product images, prices, and ASINs into our recommendations. This will make our product pages richer and let us link to specific products rather than search results.
        </p>
        <p style={s.p}>
          This does <strong>not</strong> change the affiliate relationship — same partner ID, same commission rate, same 24-hour window. It just means the link goes to <code style={s.code}>https://www.amazon.com/dp/&lt;ASIN&gt;?tag=diffr20-20</code> instead of a search URL.
        </p>

        <Hr />

        <H2>Questions</H2>
        <p style={s.p}>
          Email <A href="mailto:diffr@truake.com">diffr@truake.com</A> with &ldquo;Affiliate&rdquo; in the subject line.
        </p>
        <p style={s.p}>
          For Amazon&apos;s own disclosure rules: <A href="https://affiliate-program.amazon.com/help/operating/agreement" target="_blank">https://affiliate-program.amazon.com/help/operating/agreement</A>
          <br />
          For eBay Partner Network&apos;s: <A href="https://partnernetwork.ebay.com/agreements" target="_blank">https://partnernetwork.ebay.com/agreements</A>
        </p>

        <FooterLinks current="affiliate-disclosure" />
      </article>
    </main>
  );
}

/* ── Shared layout pieces ── */

function Header({ label }: { label: string }) {
  return (
    <header style={{ borderBottom: "1px solid rgba(42,38,32,0.15)", padding: "20px 40px", display: "flex", alignItems: "center", justifyContent: "space-between", background: "#F8F5F1" }}>
      <Link href="/diffr" style={{ fontFamily: "var(--font-syne), sans-serif", fontWeight: 800, fontSize: "1.1rem", letterSpacing: "0.08em", color: "#1B8BF5", textDecoration: "none", textTransform: "uppercase" as const }}>
        Diffr
      </Link>
      <span style={{ fontSize: "0.75rem", letterSpacing: "0.12em", textTransform: "uppercase" as const, color: "rgba(42,38,32,0.45)" }}>{label}</span>
    </header>
  );
}

function FooterLinks({ current }: { current: "privacy" | "terms" | "support" | "affiliate-disclosure" }) {
  const links = [
    { href: "/diffr",                         label: "← Back to Diffr" },
    { href: "/diffr/privacy",                 label: "Privacy" },
    { href: "/diffr/terms",                   label: "Terms" },
    { href: "/diffr/support",                 label: "Support" },
    { href: "/diffr/affiliate-disclosure",    label: "Affiliate Disclosure" },
  ];
  return (
    <div style={{ marginTop: "64px", paddingTop: "32px", borderTop: "1px solid rgba(42,38,32,0.15)", display: "flex", gap: "24px", flexWrap: "wrap" as const }}>
      {links.map(l => {
        const isActive = l.href === `/diffr/${current}`;
        return (
          <Link
            key={l.href}
            href={l.href}
            style={{
              fontSize: "0.8rem",
              letterSpacing: "0.08em",
              textTransform: "uppercase" as const,
              color: isActive ? "rgba(42,38,32,0.35)" : "#1B8BF5",
              textDecoration: "none",
              pointerEvents: isActive ? "none" as const : "auto" as const,
            }}
          >
            {l.label}
          </Link>
        );
      })}
    </div>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 style={{ fontFamily: "var(--font-syne), sans-serif", fontWeight: 700, fontSize: "1rem", letterSpacing: "0.06em", textTransform: "uppercase" as const, color: "#2A2620", margin: "0 0 14px", paddingBottom: "8px", borderBottom: "2px solid #1B8BF5", display: "inline-block" }}>
      {children}
    </h2>
  );
}

function Hr() {
  return <hr style={{ border: "none", borderTop: "1px solid rgba(42,38,32,0.12)", margin: "36px 0" }} />;
}

function Ul({ children }: { children: React.ReactNode }) {
  return <ul style={{ listStyle: "none", padding: 0, margin: "0 0 14px" }}>{children}</ul>;
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li style={{ fontSize: "0.93rem", lineHeight: 1.8, color: "#2A2620", paddingLeft: "16px", marginBottom: "8px", position: "relative" }}>
      <span style={{ position: "absolute", left: 0, top: "0.58em", width: "5px", height: "5px", borderRadius: "50%", background: "#F0522C", display: "inline-block" }} />
      {children}
    </li>
  );
}

function A({ href, children, target, rel }: { href: string; children: React.ReactNode; target?: string; rel?: string }) {
  return (
    <a
      href={href}
      target={target}
      rel={rel ?? (target === "_blank" ? "noopener noreferrer" : undefined)}
      style={{ color: "#1B8BF5", textDecoration: "underline", textDecorationColor: "rgba(27,139,245,0.4)", textUnderlineOffset: "3px" }}
    >
      {children}
    </a>
  );
}

function Table({ headers, rows }: { headers: string[]; rows: (React.ReactNode | string)[][] }) {
  return (
    <div style={{ overflowX: "auto", margin: "0 0 16px" }}>
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.875rem", lineHeight: 1.65 }}>
        <thead>
          <tr>
            {headers.map((h, i) => (
              <th key={i} style={{ textAlign: "left", padding: "10px 14px", background: "#F0522C", color: "#fff", fontFamily: "var(--font-syne), sans-serif", fontWeight: 700, fontSize: "0.7rem", letterSpacing: "0.1em", textTransform: "uppercase" as const, borderRight: i < headers.length - 1 ? "1px solid rgba(255,255,255,0.2)" : "none" }}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, ri) => (
            <tr key={ri} style={{ background: ri % 2 === 0 ? "#F8F5F1" : "#F0EBE3" }}>
              {row.map((cell, ci) => (
                <td key={ci} style={{ padding: "10px 14px", color: "#2A2620", borderBottom: "1px solid rgba(42,38,32,0.08)", borderRight: ci < row.length - 1 ? "1px solid rgba(42,38,32,0.08)" : "none", verticalAlign: "top" }}>
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

const s = {
  h1:   { fontFamily: "var(--font-syne), sans-serif", fontWeight: 800, fontSize: "clamp(2rem, 5vw, 3rem)", letterSpacing: "-0.02em", lineHeight: 1.1, margin: "0 0 10px", color: "#1B8BF5" },
  meta: { fontSize: "0.78rem", letterSpacing: "0.1em", textTransform: "uppercase" as const, color: "rgba(42,38,32,0.5)", margin: "0 0 36px" },
  p:    { fontSize: "0.93rem", lineHeight: 1.8, color: "#2A2620", margin: "0 0 14px" },
  code: { fontFamily: "var(--font-mono), monospace", fontSize: "0.82em", background: "rgba(27,139,245,0.1)", color: "#1B8BF5", padding: "1px 5px", borderRadius: "2px" },
};
