import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Affiliate Disclosure — Diffr",
  description:
    "FTC-required disclosure of Diffr's affiliate relationships with Amazon, eBay, and Walmart. We earn commission on qualifying purchases at no extra cost to you.",
  robots: { index: true, follow: true },
};

export default function DiffrAffiliateDisclosurePage() {
  return (
    <main style={{ minHeight: "100vh", background: "#F0EBE3", color: "#2A2620", fontFamily: "var(--font-syne), Georgia, serif", padding: "0 0 80px" }}>
      <Header label="Affiliate Disclosure" />
      <article style={{ maxWidth: "760px", margin: "0 auto", padding: "64px 32px 0" }}>

        <h1 style={s.h1}>Affiliate Disclosure</h1>
        <p style={s.meta}>Last updated: May 26, 2026</p>

        {/* FTC callout box */}
        <div style={{ background: "#FEF6E4", padding: "20px 24px", borderRadius: 10, borderLeft: "4px solid #F0522C", marginBottom: 36 }}>
          <p style={{ ...s.p, margin: 0 }}>
            <strong>FTC Required Disclosure:</strong> Diffr participates in affiliate
            advertising programs that provide a means for us to earn commissions by
            linking to products on third-party marketplaces. We may earn a commission
            on qualifying purchases made through our links, <strong>at no additional
            cost to you</strong>.
          </p>
        </div>

        <Hr />

        <H2>Amazon Associates Program</H2>
        <p style={s.p}>
          Diffr is a participant in the Amazon Services LLC Associates Program, an
          affiliate advertising program designed to provide a means for sites to earn
          advertising fees by advertising and linking to{" "}
          <A href="https://www.amazon.com" target="_blank" rel="sponsored nofollow">amazon.com</A>.
        </p>
        <p style={s.p}>
          As an Amazon Associate, Diffr earns from qualifying purchases. Our Amazon
          Associate tag is <code style={s.code}>diffr20-20</code>. Links to Amazon products
          on our platform may contain this tag.
        </p>

        <Hr />

        <H2>eBay Partner Network</H2>
        <p style={s.p}>
          Diffr participates in the eBay Partner Network (EPN) and uses the eBay Browse
          API under the eBay Developers Program. We display publicly available product
          data and may earn a commission on traffic referred to{" "}
          <A href="https://www.ebay.com" target="_blank" rel="sponsored nofollow">ebay.com</A>{" "}
          that results in a qualifying transaction.
        </p>

        <Hr />

        <H2>Walmart Creator Program</H2>
        <p style={s.p}>
          Diffr participates in the Walmart Creator Program, administered through
          Impact.com. We may earn a commission on purchases referred to{" "}
          <A href="https://www.walmart.com" target="_blank" rel="sponsored nofollow">walmart.com</A>{" "}
          via our links.
        </p>

        <Hr />

        <H2>What This Means for You</H2>
        <Ul>
          <Li>
            You pay <strong>the exact same price</strong> whether you navigate directly
            to Amazon, eBay, or Walmart or go through a Diffr link. Our commission is
            paid by the retailer, not added to your purchase.
          </Li>
          <Li>
            Diffr earns a <strong>small commission</strong> (typically 2–10% depending
            on product category) on items purchased after clicking our links.
          </Li>
          <Li>
            This commission model is how Diffr remains <strong>free to download and use</strong>{" "}
            without charging users or selling advertising.
          </Li>
          <Li>
            We <strong>do not receive payment</strong> to recommend specific brands or
            products. Our editorial picks and six-axis scores are calculated by our
            internal algorithm using public product data, and no brand can pay to improve
            its Diffr ranking.
          </Li>
        </Ul>

        <Hr />

        <H2>Identifying Affiliate Links</H2>
        <p style={s.p}>
          Within the Diffr iOS app, all retailer links (buttons labeled{" "}
          <code style={s.code}>Buy on Amazon</code>,{" "}
          <code style={s.code}>Buy on eBay</code>, or{" "}
          <code style={s.code}>Buy on Walmart</code>) are affiliate links.
        </p>
        <p style={s.p}>
          On this website, affiliate links carry{" "}
          <code style={s.code}>rel=&quot;sponsored nofollow&quot;</code> attributes as
          required by FTC guidelines and Google Search policies.
        </p>

        <Hr />

        <H2>Our Editorial Independence</H2>
        <p style={s.p}>
          Brand rankings, scores, and recommendations on Diffr are generated by our
          internal six-axis scoring algorithm using public product data, pricing,
          community reviews, and editorial research.{" "}
          <strong>No brand can pay to improve its Diffr score or ranking.</strong>
        </p>
        <p style={s.p}>
          If we ever introduce sponsored placements or paid brand features, they will be
          clearly and prominently labeled as such — distinct from our editorially-scored
          content.
        </p>
        <p style={s.p}>
          Affiliate relationships do not influence which brands or products appear in
          Beginner Packs or Scenes. Curation is based on score quality and beginner
          relevance, not commission rates.
        </p>

        <Hr />

        <H2>Questions</H2>
        <p style={s.p}>
          If you have questions about this disclosure or our affiliate relationships,
          email us at{" "}
          <A href="mailto:diffr@truake.com">diffr@truake.com</A>.
        </p>

        <FooterLinks current="affiliate-disclosure" />
      </article>
    </main>
  );
}

/* ── Shared sub-components ── */

function Header({ label }: { label: string }) {
  return (
    <header style={{ borderBottom: "1px solid rgba(42,38,32,0.15)", padding: "20px 40px", display: "flex", alignItems: "center", justifyContent: "space-between", background: "#F8F5F1" }}>
      <Link href="/diffr" style={{ fontFamily: "var(--font-syne), sans-serif", fontWeight: 800, fontSize: "1.1rem", letterSpacing: "0.08em", color: "#1B8BF5", textDecoration: "none", textTransform: "uppercase" as const }}>
        Diffr
      </Link>
      <span style={{ fontSize: "0.75rem", letterSpacing: "0.12em", textTransform: "uppercase" as const, color: "rgba(42,38,32,0.45)" }}>{label}</span>
    </header>
  );
}

function FooterLinks({ current }: { current: "privacy" | "terms" | "support" | "affiliate-disclosure" }) {
  const links = [
    { href: "/diffr",                         label: "← Back to Diffr" },
    { href: "/diffr/privacy",                 label: "Privacy" },
    { href: "/diffr/terms",                   label: "Terms" },
    { href: "/diffr/support",                 label: "Support" },
    { href: "/diffr/affiliate-disclosure",    label: "Affiliate Disclosure" },
  ];
  return (
    <div style={{ marginTop: "64px", paddingTop: "32px", borderTop: "1px solid rgba(42,38,32,0.15)", display: "flex", gap: "24px", flexWrap: "wrap" as const }}>
      {links.map(l => {
        const isActive = l.href === `/diffr/${current}`;
        return (
          <Link
            key={l.href}
            href={l.href}
            style={{
              fontSize: "0.8rem",
              letterSpacing: "0.08em",
              textTransform: "uppercase" as const,
              color: isActive ? "rgba(42,38,32,0.35)" : "#1B8BF5",
              textDecoration: "none",
              pointerEvents: isActive ? "none" as const : "auto" as const,
            }}
          >
            {l.label}
          </Link>
        );
      })}
    </div>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 style={{ fontFamily: "var(--font-syne), sans-serif", fontWeight: 700, fontSize: "1rem", letterSpacing: "0.06em", textTransform: "uppercase" as const, color: "#2A2620", margin: "0 0 14px", paddingBottom: "8px", borderBottom: "2px solid #1B8BF5", display: "inline-block" }}>
      {children}
    </h2>
  );
}

function Hr() {
  return <hr style={{ border: "none", borderTop: "1px solid rgba(42,38,32,0.12)", margin: "36px 0" }} />;
}

function Ul({ children }: { children: React.ReactNode }) {
  return <ul style={{ listStyle: "none", padding: 0, margin: "0 0 14px" }}>{children}</ul>;
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li style={{ fontSize: "0.93rem", lineHeight: 1.8, color: "#2A2620", paddingLeft: "16px", marginBottom: "8px", position: "relative" }}>
      <span style={{ position: "absolute", left: 0, top: "0.58em", width: "5px", height: "5px", borderRadius: "50%", background: "#F0522C", display: "inline-block" }} />
      {children}
    </li>
  );
}

function A({ href, children, target, rel }: { href: string; children: React.ReactNode; target?: string; rel?: string }) {
  return (
    <a
      href={href}
      target={target}
      rel={rel ?? (target === "_blank" ? "noopener noreferrer" : undefined)}
      style={{ color: "#1B8BF5", textDecoration: "underline", textDecorationColor: "rgba(27,139,245,0.4)", textUnderlineOffset: "3px" }}
    >
      {children}
    </a>
  );
}

const s = {
  h1:   { fontFamily: "var(--font-syne), sans-serif", fontWeight: 800, fontSize: "clamp(2rem, 5vw, 3rem)", letterSpacing: "-0.02em", lineHeight: 1.1, margin: "0 0 10px", color: "#1B8BF5" },
  meta: { fontSize: "0.78rem", letterSpacing: "0.1em", textTransform: "uppercase" as const, color: "rgba(42,38,32,0.5)", margin: "0 0 36px" },
  p:    { fontSize: "0.93rem", lineHeight: 1.8, color: "#2A2620", margin: "0 0 14px" },
  code: { fontFamily: "var(--font-mono), monospace", fontSize: "0.82em", background: "rgba(27,139,245,0.1)", color: "#1B8BF5", padding: "1px 5px", borderRadius: "2px" },
};
